name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build App
        run: |
          xcodebuild -project BatteryMonitor.xcodeproj \
            -scheme BatteryMonitor \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create DMG
        run: |
          npm install -g create-dmg
          ls -la build/Build/Products/Release/
          create-dmg \
            --volname "Battery Monitor" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --app-drop-link 600 185 \
            --background-color 0xFFFFFF \
            "BatteryMonitor.dmg" \
            "build/Build/Products/Release/BatteryMonitor.app" || exit 1

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: BatteryMonitor.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
