name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Import Certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

          # Import certificate
          echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          # Verify certificate import
          security find-identity -v -p codesigning build.keychain

      - name: Build App
        run: |
          CERTIFICATE_ID=$(security find-identity -v -p codesigning build.keychain | grep "Mac Development" | head -1 | awk '{print $2}')
          xcodebuild -project BatteryMonitor.xcodeproj \
            -scheme BatteryMonitor \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="$CERTIFICATE_ID" \
            OTHER_CODE_SIGN_FLAGS="--keychain build.keychain"

      - name: Create DMG
        run: |
          cd build/Build/Products/Release/
          CERTIFICATE_ID=$(security find-identity -v -p codesigning build.keychain | grep "Mac Development" | head -1 | awk '{print $2}')
          codesign --force --deep --sign "$CERTIFICATE_ID" --keychain build.keychain BatteryMonitor.app
          hdiutil create -volname "Battery Monitor" -srcfolder BatteryMonitor.app -ov -format UDZO BatteryMonitor.dmg
          codesign --force --sign "$CERTIFICATE_ID" --keychain build.keychain BatteryMonitor.dmg

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Build/Products/Release/BatteryMonitor.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
